-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建密码哈希函数
CREATE OR REPLACE FUNCTION hash_password(password TEXT)
RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
AS $$
  SELECT crypt(password, gen_salt('bf', 4));
$$;

-- 创建密码验证函数
CREATE OR REPLACE FUNCTION verify_password(password_hash TEXT, password TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
IMMUTABLE
AS $$
  SELECT crypt(password, password_hash) = password_hash;
$$;