-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "允许匿名用户查询用户" ON users
  FOR SELECT
  TO anon
  USING (true);

CREATE POLICY "允许认证用户查询用户" ON users
  FOR SELECT
  TO authenticated
  USING (true);