-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 配置 Google OAuth 提供商
-- 创建 OAuth 配置表
CREATE TABLE IF NOT EXISTS public.oauth_config (
  id SERIAL PRIMARY KEY,
  provider VARCHAR(50) NOT NULL UNIQUE,
  client_id TEXT NOT NULL,
  client_secret TEXT NOT NULL,
  api_key TEXT,
  enabled BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 插入 Google OAuth 配置
-- 注意：请替换为你自己的 OAuth 凭证
INSERT INTO public.oauth_config (provider, client_id, client_secret, api_key, enabled)
VALUES (
  'google',
  'YOUR_GOOGLE_CLIENT_ID',
  'YOUR_GOOGLE_CLIENT_SECRET',
  'YOUR_GOOGLE_API_KEY',
  true
)
ON CONFLICT (provider) DO UPDATE SET
  client_id = EXCLUDED.client_id,
  client_secret = EXCLUDED.client_secret,
  api_key = EXCLUDED.api_key,
  enabled = EXCLUDED.enabled,
  updated_at = NOW();

-- 启用 RLS
ALTER TABLE public.oauth_config ENABLE ROW LEVEL SECURITY;

-- 创建策略：允许匿名用户查看配置
CREATE POLICY "允许查看 OAuth 配置" ON public.oauth_config
  FOR SELECT USING (true);