-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 用户表
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(100) UNIQUE,
  phone VARCHAR(20) UNIQUE,
  password_hash VARCHAR(255),
  wallet_address VARCHAR(100) UNIQUE,
  nickname VARCHAR(50) NOT NULL DEFAULT 'User',
  avatar TEXT DEFAULT 'https://api.dicebear.com/7.x/avataaars/svg?seed=default',
  kyc_level SMALLINT DEFAULT 0,
  vip_level SMALLINT DEFAULT 0,
  vip_expire_at TIMESTAMP,
  invite_code VARCHAR(20) UNIQUE NOT NULL,
  inviter_id UUID REFERENCES users(id),
  points INTEGER DEFAULT 0,
  token_balance DECIMAL(20,8) DEFAULT 0,
  language VARCHAR(10) DEFAULT 'zh',
  timezone VARCHAR(50) DEFAULT 'Asia/Shanghai',
  status SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 短剧表
CREATE TABLE IF NOT EXISTS dramas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title JSON NOT NULL,
  description JSON,
  cover_image TEXT NOT NULL,
  category_id UUID,
  total_episodes INTEGER DEFAULT 0,
  vip_level SMALLINT DEFAULT 0,
  status SMALLINT DEFAULT 1,
  release_date DATE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 剧集表
CREATE TABLE IF NOT EXISTS episodes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  drama_id UUID NOT NULL REFERENCES dramas(id) ON DELETE CASCADE,
  episode_num INTEGER NOT NULL,
  title JSON NOT NULL,
  video_url TEXT,
  duration INTEGER DEFAULT 0,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- IPT资产表
CREATE TABLE IF NOT EXISTS assets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  cover TEXT,
  description TEXT,
  target_amount DECIMAL(20,8) NOT NULL,
  raised_amount DECIMAL(20,8) DEFAULT 0,
  apy DECIMAL(5,2) DEFAULT 0,
  duration_days INTEGER DEFAULT 0,
  status SMALLINT DEFAULT 0,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 用户持仓表
CREATE TABLE IF NOT EXISTS positions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  asset_id UUID NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  amount DECIMAL(20,8) NOT NULL DEFAULT 0,
  cost_price DECIMAL(20,8) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, asset_id)
);

-- 交易订单表
CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  asset_id UUID NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  type SMALLINT NOT NULL,
  price DECIMAL(20,8) NOT NULL,
  amount DECIMAL(20,8) NOT NULL,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 质押池表
CREATE TABLE IF NOT EXISTS stake_pools (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(50) NOT NULL,
  lock_days INTEGER NOT NULL DEFAULT 0,
  base_apy DECIMAL(5,2) NOT NULL DEFAULT 0,
  vip_bonus DECIMAL(5,2) DEFAULT 0,
  max_stake DECIMAL(20,8),
  total_staked DECIMAL(20,8) DEFAULT 0,
  status SMALLINT DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 用户质押记录表
CREATE TABLE IF NOT EXISTS stake_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pool_id UUID NOT NULL REFERENCES stake_pools(id) ON DELETE CASCADE,
  amount DECIMAL(20,8) NOT NULL DEFAULT 0,
  vip_level_at_stake SMALLINT DEFAULT 0,
  lock_end_time TIMESTAMP,
  total_earned DECIMAL(20,8) DEFAULT 0,
  pending_earned DECIMAL(20,8) DEFAULT 0,
  auto_compound BOOLEAN DEFAULT FALSE,
  status SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 任务表
CREATE TABLE IF NOT EXISTS tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  type SMALLINT NOT NULL,
  description TEXT,
  condition_type VARCHAR(50) NOT NULL,
  condition_value JSON,
  reward_points INTEGER DEFAULT 0,
  reward_token DECIMAL(20,8) DEFAULT 0,
  sort_order INTEGER DEFAULT 0,
  status SMALLINT DEFAULT 1,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 用户任务记录表
CREATE TABLE IF NOT EXISTS user_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  progress INTEGER DEFAULT 0,
  target INTEGER DEFAULT 0,
  status SMALLINT DEFAULT 0,
  completed_at TIMESTAMP,
  claimed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, task_id)
);

-- 积分商城商品表
CREATE TABLE IF NOT EXISTS shop_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  type SMALLINT NOT NULL,
  points INTEGER NOT NULL DEFAULT 0,
  token_amount DECIMAL(20,8),
  vip_days INTEGER,
  stock INTEGER DEFAULT -1,
  daily_limit INTEGER DEFAULT 0,
  image TEXT,
  status SMALLINT DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 兑换记录表
CREATE TABLE IF NOT EXISTS exchange_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  item_id UUID NOT NULL REFERENCES shop_items(id) ON DELETE CASCADE,
  points_used INTEGER NOT NULL DEFAULT 0,
  quantity INTEGER DEFAULT 1,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 积分流水表
CREATE TABLE IF NOT EXISTS points_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type SMALLINT NOT NULL,
  amount INTEGER NOT NULL,
  balance_after INTEGER NOT NULL,
  source_id VARCHAR(64),
  created_at TIMESTAMP DEFAULT NOW()
);

-- 代币流水表
CREATE TABLE IF NOT EXISTS token_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type SMALLINT NOT NULL,
  amount DECIMAL(20,8) NOT NULL,
  balance_after DECIMAL(20,8) NOT NULL,
  tx_hash VARCHAR(100),
  status SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 邀请记录表
CREATE TABLE IF NOT EXISTS invite_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  inviter_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  invitee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  level SMALLINT NOT NULL DEFAULT 1,
  event_type VARCHAR(50) NOT NULL,
  reward_points INTEGER DEFAULT 0,
  reward_token DECIMAL(20,8) DEFAULT 0,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 签到记录表
CREATE TABLE IF NOT EXISTS sign_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  sign_date DATE NOT NULL,
  points_earned INTEGER DEFAULT 0,
  is_makeup BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, sign_date)
);

-- 观看记录表
CREATE TABLE IF NOT EXISTS watch_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  drama_id UUID NOT NULL REFERENCES dramas(id) ON DELETE CASCADE,
  episode_id UUID NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
  watch_duration INTEGER DEFAULT 0,
  is_completed BOOLEAN DEFAULT FALSE,
  has_interaction BOOLEAN DEFAULT FALSE,
  device_fingerprint VARCHAR(64),
  ip_address VARCHAR(45),
  created_at TIMESTAMP DEFAULT NOW()
);

-- 公告表
CREATE TABLE IF NOT EXISTS announcements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title VARCHAR(200) NOT NULL,
  content TEXT,
  is_important BOOLEAN DEFAULT FALSE,
  status SMALLINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_users_inviter ON users(inviter_id);
CREATE INDEX IF NOT EXISTS idx_positions_user ON positions(user_id);
CREATE INDEX IF NOT EXISTS idx_positions_asset ON positions(asset_id);
CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_asset ON orders(asset_id);
CREATE INDEX IF NOT EXISTS idx_stake_records_user ON stake_records(user_id);
CREATE INDEX IF NOT EXISTS idx_user_tasks_user ON user_tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_user_tasks_task ON user_tasks(task_id);
CREATE INDEX IF NOT EXISTS idx_points_transactions_user ON points_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_token_transactions_user ON token_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_invite_records_inviter ON invite_records(inviter_id);
CREATE INDEX IF NOT EXISTS idx_watch_records_user ON watch_records(user_id);
CREATE INDEX IF NOT EXISTS idx_watch_records_drama ON watch_records(drama_id);

-- 启用RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE dramas ENABLE ROW LEVEL SECURITY;
ALTER TABLE episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE stake_pools ENABLE ROW LEVEL SECURITY;
ALTER TABLE stake_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE shop_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE exchange_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE points_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE token_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE invite_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE sign_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE watch_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;